declare namespace Cloudflare {
  interface Env {
    DB?: D1Database;
    BUCKET?: R2Bucket;
    HELIUS_API_KEY?: string;
    JUPITER_API_KEY?: string;
    MAINNET_EXECUTION_ENABLED?: string;
    SOLANA_REWARD_TREASURY_ADDRESS?: string;
    SOLANA_BUYBACK_TREASURY_ADDRESS?: string;
    SPORTPAD_MINT_ADDRESS?: string;
    SPORTPAD_PUBLICATION_MODE?: string;
    SPORTPAD_OPERATOR_USER_IDS?: string;
    SPORTPAD_ALLOW_SELF_REVIEW?: string;
    SPORTPAD_SETTLEMENT_ENABLED?: string;
    SPORTPAD_REWARDS_ENABLED?: string;
    SPORTPAD_HOLDER_INDEXER_ENABLED?: string;
    SPORTPAD_CLAIMS_ENABLED?: string;
    SPORTPAD_BUYBACK_ENABLED?: string;
    SPORTPAD_SIGNER_PROVIDER?: string;
    SPORTPAD_WORKER_TOKEN?: string;
    SOLANA_FEE_COLLECTOR_KEY_REF?: string;
    SOLANA_REWARD_VAULT_KEY_REF?: string;
    SOLANA_BUYBACK_EXECUTOR_KEY_REF?: string;
    CHILIZ_REPLENISHER_KEY_REF?: string;
  }
}
