export type RewardAssetCategory = "Football" | "Motorsport" | "Combat" | "Esports" | "Rugby" | "Tennis";

export type RewardAsset = {
  symbol: string;
  name: string;
  category: RewardAssetCategory;
  solanaMint: string;
  imagePath: string;
  executionStatus: "not_enabled";
  source: string;
};

const OFFICIAL_REGISTRY = "https://docs.chiliz.com/quick-start/token-contract-addresses";

// Snapshot of the official Chiliz cross-chain Fan Token registry.
// Every entry below has an official Solana mint in the cited registry.
export const REWARD_ASSETS: ReadonlyArray<RewardAsset> = [
  {
    symbol: "ACM",
    name: "AC Milan",
    category: "Football",
    solanaMint: "H5qGPniSX2uCNtAnxr7RpdfFAZcGkr6dknjgpa1AKHe1",
    imagePath: "/fan-tokens/ACM.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "AFC",
    name: "Arsenal FC",
    category: "Football",
    solanaMint: "Dst93spXQEXxFzwYbFrQRnFYBYpw7AzB2QyALEeP4NGQ",
    imagePath: "/fan-tokens/AFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ALA",
    name: "Alanyaspor",
    category: "Football",
    solanaMint: "7hoDr3WJbQD25b2foZqEretHUD4fY1MWkKNp1dytnY2v",
    imagePath: "/fan-tokens/ALA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ALL",
    name: "Alliance",
    category: "Esports",
    solanaMint: "HkeMF6QnfVGwhvHTKJxtkyeiFjyYUESfgzBwGojtyJ4X",
    imagePath: "/fan-tokens/ALL.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "AM",
    name: "Aston Martin Cognizant",
    category: "Motorsport",
    solanaMint: "5FnbDoHAX9Dsu27pTcZpmj6VU3YUmjqqWLz6tXYZwy2P",
    imagePath: "/fan-tokens/AM.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "APL",
    name: "Apollon Limassol FC",
    category: "Football",
    solanaMint: "ff3G7QPz7MtYB2ZcfC6Tj9PUWZBPGE8zygc764a8Jwi",
    imagePath: "/fan-tokens/APL.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ARG",
    name: "Argentina",
    category: "Football",
    solanaMint: "BX8VbHBf8DUHeGJjJsSW2HCviGyQSF5SVCEnN7vXUkwM",
    imagePath: "/fan-tokens/ARG.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ASM",
    name: "AS Monaco",
    category: "Football",
    solanaMint: "A2XmL1189cLLdueuUBKggSJkCymz3Q6xpeqba5VzhvLN",
    imagePath: "/fan-tokens/ASM.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ASR",
    name: "AS Roma",
    category: "Football",
    solanaMint: "3cVuTnMj8FeqK82PDgK4JzKnLP7LM6GauqTyqnxtcSk1",
    imagePath: "/fan-tokens/ASR.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ATLAS",
    name: "Atlas FC",
    category: "Football",
    solanaMint: "2YSJqm3apDBCwv5a9bHV63Rexuo24grTzd8K9EZ1yDZp",
    imagePath: "/fan-tokens/ATLAS.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ATM",
    name: "Atlético de Madrid",
    category: "Football",
    solanaMint: "6VdpC1hcx7byFtJ5M6Xhspa6Uup5rZHruzXvuJhXAyXm",
    imagePath: "/fan-tokens/ATM.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "AVL",
    name: "Aston Villa",
    category: "Football",
    solanaMint: "4o89KZs6pMf1YU2iXQcguquroJySET8rpXUz9sBG2q46",
    imagePath: "/fan-tokens/AVL.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "BAHIA",
    name: "EC Bahia",
    category: "Football",
    solanaMint: "4dwQdsgtPz3BM9frebdqp4f7v9mLmstppefdw1vjixEh",
    imagePath: "/fan-tokens/BAHIA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "BAR",
    name: "FC Barcelona",
    category: "Football",
    solanaMint: "82DNsTK61ZrgCHP6pfP32Eubcsp9h38d64E6X9ETEBBe",
    imagePath: "/fan-tokens/BAR.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "BELG",
    name: "Belgium National Team",
    category: "Football",
    solanaMint: "2aYxvDB3JvJwzGRiDWeiSk1rGpGQj8s2w66dVQvhcKmF",
    imagePath: "/fan-tokens/BELG.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "BENFICA",
    name: "SL Benfica",
    category: "Football",
    solanaMint: "HD9i9C2Pw6hWXm354i3SWkYG8ZtfikUJn2bNPzwQZcEK",
    imagePath: "/fan-tokens/BENFICA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "BFC",
    name: "Bologna FC",
    category: "Football",
    solanaMint: "J7dBeunETSUx7dPCibsK7oNsz6QNDbLTUv3Kw2YFT5VT",
    imagePath: "/fan-tokens/BFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "BUFC",
    name: "BALI UNITED",
    category: "Football",
    solanaMint: "3pBn4BrVMsS93Lytj6Cf28WbxsJXdGevVb2iedywmk61",
    imagePath: "/fan-tokens/BUFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "CAI",
    name: "Club Atlético Independiente",
    category: "Football",
    solanaMint: "2zNLNYHfZGvDSQL29NrWNzPbenzWYSDUDH2c8Rxy9xfW",
    imagePath: "/fan-tokens/CAI.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "CHVS",
    name: "Chivas",
    category: "Football",
    solanaMint: "BJpndXvh37zEg5TQd5KcWzvyvycDTuo7uCRnHpq8GoCA",
    imagePath: "/fan-tokens/CHVS.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "CITY",
    name: "Manchester City FC",
    category: "Football",
    solanaMint: "8WbNQtY7QmXMVKJFTSqFudierVZZtbuoyeepZEqJ1B2w",
    imagePath: "/fan-tokens/CITY.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "CPFC",
    name: "Crystal Palace",
    category: "Football",
    solanaMint: "34R8NsHYctkbXJ6yxKfyStFLuWbeioJiRKbY5Vn9eyry",
    imagePath: "/fan-tokens/CPFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "DAVIS",
    name: "Davis Cup",
    category: "Tennis",
    solanaMint: "DGBGtBwKKX3yCJGTtVDPE75uGN26p4ME6iSfQMuYQvb5",
    imagePath: "/fan-tokens/DAVIS.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "DOJO",
    name: "Ninjas in Pyjamas",
    category: "Esports",
    solanaMint: "8gcvHCxXWUNcpD4QahroPCoZExTKNMUwdmFCG4jsd9Wg",
    imagePath: "/fan-tokens/DOJO.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "DZG",
    name: "Dinamo Zagreb",
    category: "Football",
    solanaMint: "GhVytg7CjbJkD4fSSs88p73wiSjRVkd1qxkPPf9whtmJ",
    imagePath: "/fan-tokens/DZG.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "EFC",
    name: "Everton Football Club",
    category: "Football",
    solanaMint: "HomA6eCphSyYBEPEEGj8xtjehstxj1B6xE46A78HFPAb",
    imagePath: "/fan-tokens/EFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ENDCEX",
    name: "Endpoint CeX",
    category: "Esports",
    solanaMint: "64kjfQvxn3NmnjGDCspiiY6zoG4RENzbtSLa4h8AmARA",
    imagePath: "/fan-tokens/ENDCEX.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "FLU",
    name: "Fluminense FC",
    category: "Football",
    solanaMint: "EHt5kkDVXNy6NRscbDwGkiVjTsuzd88iaGokzJMgKb4F",
    imagePath: "/fan-tokens/FLU.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "FOR",
    name: "Fortuna Sittard",
    category: "Football",
    solanaMint: "AKnvKK4MRa7TNp8w7CE7wnQfFKxNbqm86Z3Czno4p1Eo",
    imagePath: "/fan-tokens/FOR.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "GAL",
    name: "Galatasaray S.K.",
    category: "Football",
    solanaMint: "EDzhmkPa5gToYGowjH66xycCRgPmfWNzfqpXdCzsYb8M",
    imagePath: "/fan-tokens/GAL.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "GALO",
    name: "Clube Atlético Mineiro",
    category: "Football",
    solanaMint: "HJDTyM8uTpdVfW4KSjXJnFXKDVg7czRxDm3d7PJD9PTd",
    imagePath: "/fan-tokens/GALO.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "GFK",
    name: "Gaziantep FK",
    category: "Football",
    solanaMint: "9j3NcycGz2XGPcKckfozu35rZz8gagHcb15CSyCXHcxv",
    imagePath: "/fan-tokens/GFK.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "GOZ",
    name: "Goztepe S.K.",
    category: "Football",
    solanaMint: "HC3jUdgy3r66RPc9hbAq6ia88ARChVPcdxDkCmQJELtt",
    imagePath: "/fan-tokens/GOZ.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "HASHTAG",
    name: "Hashtag United F.C.",
    category: "Football",
    solanaMint: "Faq1MPrFgxbAvQH1pqH3rGgK5vKBQWrXNmsG81Pq12SD",
    imagePath: "/fan-tokens/HASHTAG.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "IBFK",
    name: "İstanbul Başakşehir FK",
    category: "Football",
    solanaMint: "Dqb6YKsEHq6agB5FbMCBnmF3RkthDrC7izBpeSArgXxb",
    imagePath: "/fan-tokens/IBFK.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "INTER",
    name: "Inter Milan",
    category: "Football",
    solanaMint: "HagS3VmAuhx5QJnHcuMAJF4wwVDE58CiX5SFZCYFrVe",
    imagePath: "/fan-tokens/INTER.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ITA",
    name: "FIGC",
    category: "Football",
    solanaMint: "Gi7tY2BixXnj9XiSFFRFbjJ2h4Su146h6iF4ipALaDuX",
    imagePath: "/fan-tokens/ITA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "JDT",
    name: "Johor Darul Ta'zim F.C",
    category: "Football",
    solanaMint: "Bhe7kDxUcW5e51eavqW3fRqtJiHYPDDNYgLjCwwLTegn",
    imagePath: "/fan-tokens/JDT.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "JUV",
    name: "Juventus",
    category: "Football",
    solanaMint: "HE6bLNs16qgQo2jVSMXDSCnxQahjdVrww7qQPrHrZtEw",
    imagePath: "/fan-tokens/JUV.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "LEG",
    name: "Legia Warsaw",
    category: "Football",
    solanaMint: "HW1hgpqo5njF5yDGe7tkKEgYzYHmyU4QwizXQs3pgC2G",
    imagePath: "/fan-tokens/LEG.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "LEV",
    name: "Levante",
    category: "Football",
    solanaMint: "4xMWy86qhjMGkWkfbxTtRfiXC1k2WDc8DBfEVuXeUpgh",
    imagePath: "/fan-tokens/LEV.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "LUFC",
    name: "Leeds United FC",
    category: "Football",
    solanaMint: "HLTTFNhUSTPUVfAfNoDLMfjPNuY9fQEr2cNYCvEeLHZS",
    imagePath: "/fan-tokens/LUFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "MENGO",
    name: "Flamengo",
    category: "Football",
    solanaMint: "Hf5terE5YuL2e8um8398r6vbsiNcfvwggwUAssgAxeF3",
    imagePath: "/fan-tokens/MENGO.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "MFC",
    name: "Millonarios",
    category: "Football",
    solanaMint: "3FXSFArHJw96KoQjFMc2PCm7hMJPT8gyYLvnnascQQVW",
    imagePath: "/fan-tokens/MFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "MIBR",
    name: "MIBR",
    category: "Esports",
    solanaMint: "C9fjwEYf3UL1SULNnZAWmKum288wMTSchppCwKwTSAUS",
    imagePath: "/fan-tokens/MIBR.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "NAP",
    name: "Napoli",
    category: "Football",
    solanaMint: "BjXGwMnWWUkS9JrXEkkamszu4oX8oqo3kNqFr3ifNk1F",
    imagePath: "/fan-tokens/NAP.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "NAVI",
    name: "Natus Vincere",
    category: "Esports",
    solanaMint: "4NEW5cZGFDjJJe2npyRruHCD9HZ5cZcSoarmECwZ2AfX",
    imagePath: "/fan-tokens/NAVI.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "OG",
    name: "OG",
    category: "Esports",
    solanaMint: "BtjXf3LA7Z3jxAcQkKUqKYpLFS5B7GuB7pfjzeas1tdB",
    imagePath: "/fan-tokens/OG.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "PERSIB",
    name: "PERSIB",
    category: "Football",
    solanaMint: "61CW5BDkhnqr3jSmLAHVa6fPLw7scqJm3qb9kGYdrBC",
    imagePath: "/fan-tokens/PERSIB.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "PERSIJA",
    name: "PERSIJA",
    category: "Football",
    solanaMint: "8vuNVRq1MuEtEyPcWXWpciXQRuD1BP8ZvoersHyBeb5",
    imagePath: "/fan-tokens/PERSIJA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "PFL",
    name: "Professional Fighters League",
    category: "Combat",
    solanaMint: "xcUwiJe4cfb6VKKyoMkhyqaCeEW8YexXSSxPuswytRm",
    imagePath: "/fan-tokens/PFL.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "POR",
    name: "Portugal National Team",
    category: "Football",
    solanaMint: "AiYi7HyVVXnDSuj8BoPirDsuuWgddeKkD5MQN35VpwNz",
    imagePath: "/fan-tokens/POR.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "PSG",
    name: "Paris Saint-Germain",
    category: "Football",
    solanaMint: "5eyib4qghYGHNh7VvxSFGYLFJSanjq9hug9fR52kksnm",
    imagePath: "/fan-tokens/PSG.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "QUINS",
    name: "Harlequins",
    category: "Rugby",
    solanaMint: "FuwqMR1QynJxzke5toMz3MdQ7dFBxMpLZcggeiYG2Ds",
    imagePath: "/fan-tokens/QUINS.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "RACING",
    name: "Racing Club",
    category: "Football",
    solanaMint: "HiAuh8bnjeNnv4HWwkzYSKTDyS2jjRTHfsWnbmbyvc97",
    imagePath: "/fan-tokens/RACING.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "ROUSH",
    name: "Roush Fenway Racing",
    category: "Motorsport",
    solanaMint: "2QC3rTo9tHYBG6C1WWKbGYsx8XitDu16qKn1Hw4EDWG7",
    imagePath: "/fan-tokens/ROUSH.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "RSO",
    name: "Real Sociedad",
    category: "Football",
    solanaMint: "EFiyTrx8PtWfDJFNQL5f2R2LK3h7xwMvqY6cAcUxutNQ",
    imagePath: "/fan-tokens/RSO.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SACI",
    name: "Internacional",
    category: "Football",
    solanaMint: "FqDcfNBPM23XaMQ9XRN8Tg9ZEdAtPsHKLStwBCyVcTH3",
    imagePath: "/fan-tokens/SACI.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SAFA",
    name: "South Africa National Team",
    category: "Football",
    solanaMint: "EwBBVWVueeUagquPM6HqeoE9zCUwdhu5tQCmvWhWbxnH",
    imagePath: "/fan-tokens/SAFA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SAM",
    name: "Samsunspor",
    category: "Football",
    solanaMint: "HzC7pNJ1TGZeEvXMu9mb5r3ynsvKt9VKVq3gX4bsVac5",
    imagePath: "/fan-tokens/SAM.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SAN",
    name: "Club Santos Laguna",
    category: "Football",
    solanaMint: "7jPCVLHoybJufYyXtqTQRZ96rksBCFq7zNNELQVP92hC",
    imagePath: "/fan-tokens/SAN.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SARRIES",
    name: "Saracens",
    category: "Rugby",
    solanaMint: "8Lsu76xiyf62MKscDezx29cNEFhBWUtmuoX5Vy2HT9f6",
    imagePath: "/fan-tokens/SARRIES.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SAUBER",
    name: "Stake F1® Team KICK Sauber",
    category: "Motorsport",
    solanaMint: "FX2XCcCv1qLuSagGgK8oRR7vzb9iyQgaM45DSG7gJQsF",
    imagePath: "/fan-tokens/SAUBER.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SCCP",
    name: "Corinthians",
    category: "Football",
    solanaMint: "EFgHaH3va27dKwyUJxDKT76Gx8FVQh3MgUnvKH2fyS8Q",
    imagePath: "/fan-tokens/SCCP.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SEVILLA",
    name: "Sevilla FC",
    category: "Football",
    solanaMint: "DQxhAK6riCdWuYSHUaHxvZbEs7hCGtPfeXxCzn8fp4jo",
    imagePath: "/fan-tokens/SEVILLA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SFA",
    name: "Scotland",
    category: "Football",
    solanaMint: "6mmp4rqjCqhrhdEohPNkTrJaRYxFnTHLXBShBjb48puG",
    imagePath: "/fan-tokens/SFA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SFP",
    name: "Stade Français Paris",
    category: "Rugby",
    solanaMint: "75bLB7frmaDXoVBJoeEeC6LdRxa6QusEZs5znGGGAzXN",
    imagePath: "/fan-tokens/SFP.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SHARKS",
    name: "Sharks",
    category: "Rugby",
    solanaMint: "Hhj1BWuQ2iB123XT5RCnPJX6SamPzx6uvu39pRRRJBMh",
    imagePath: "/fan-tokens/SHARKS.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SPAIN",
    name: "Spain",
    category: "Football",
    solanaMint: "5J66Ept1vhnkdWy96SFGRFkABJLu6372NoGQ4Jvnm1QF",
    imagePath: "/fan-tokens/SPAIN.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SPFC",
    name: "São Paulo FC",
    category: "Football",
    solanaMint: "25vvHsXtKnnBtno1otYJzcdVcoxR7bGqWR7FZEZh9CXn",
    imagePath: "/fan-tokens/SPFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "SPURS",
    name: "Tottenham Hotspur",
    category: "Football",
    solanaMint: "GDNoEjfSAUAvManoEaT3vStGcvwKkcUcSTvUwfvwhqXf",
    imagePath: "/fan-tokens/SPURS.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "STV",
    name: "Sint-Truidense Voetbalvereniging",
    category: "Football",
    solanaMint: "5RhF74yi3uGHjzUjVBqtkCAbsNg8PM6KgL7B85UYM2SN",
    imagePath: "/fan-tokens/STV.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "TH",
    name: "Team Heretics",
    category: "Esports",
    solanaMint: "FiVKSsRESfpevpLREzDiudTzryFQ58uUzmB9P5YwbcNS",
    imagePath: "/fan-tokens/TH.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "TIGRES",
    name: "Tigres",
    category: "Football",
    solanaMint: "2kwV7LBrEqzJR49EPsMszto3fFenu3mXr26Q1EZeYDbn",
    imagePath: "/fan-tokens/TIGRES.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "TIGERS",
    name: "Leicester Tigers",
    category: "Rugby",
    solanaMint: "4foTjmAeoN4RLz5iAWS9FPgTpdtcLzabGExCZJpbrT2P",
    imagePath: "/fan-tokens/TIGERS.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "TRA",
    name: "Trabzonspor",
    category: "Football",
    solanaMint: "AMnbxhGifp3gm2YsNwmfcF2ZCLsZN6iP3LdzBPZgGpzW",
    imagePath: "/fan-tokens/TRA.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "UCH",
    name: "Universidad de Chile",
    category: "Football",
    solanaMint: "89nUf6DFzukM3jdr73D2JdVT3Z7qZzwNnC4huaxyW8p9",
    imagePath: "/fan-tokens/UCH.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "UFC",
    name: "UFC",
    category: "Combat",
    solanaMint: "FG44Jffowai8hqQifkwtNLbADkH3EjG5txMc54yaJ4cN",
    imagePath: "/fan-tokens/UFC.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "VASCO",
    name: "Vasco da Gama",
    category: "Football",
    solanaMint: "4nQBeMMsLJXfFQRS5VnLxCCk74iVguJMhZ2etSHq1nFz",
    imagePath: "/fan-tokens/VASCO.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "VCF",
    name: "Valencia CF",
    category: "Football",
    solanaMint: "9gui2Z9dzatiJAapRd5R9CkfD5BUFot5dJppijZRQ2gA",
    imagePath: "/fan-tokens/VCF.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "VERDAO",
    name: "Palmeiras",
    category: "Football",
    solanaMint: "5qBMrbPx1CUbmqc87THJhWPy6aUkywkU3DdREqXgZ23W",
    imagePath: "/fan-tokens/VERDAO.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
  {
    symbol: "YBO",
    name: "BSC Young Boys",
    category: "Football",
    solanaMint: "BUYgeUDgnRxnu9G5sPyoHwigTL4PrqMSd4LURwH1KE4G",
    imagePath: "/fan-tokens/YBO.png",
    executionStatus: "not_enabled",
    source: OFFICIAL_REGISTRY,
  },
];

export function getRewardAsset(symbol: string) {
  return REWARD_ASSETS.find((asset) => asset.symbol === symbol.toUpperCase());
}
